name: Main

on: 
  push:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: prefix-dev/setup-pixi@v0.10.2
        with:
          pixi-version: v0.68.1
      - name: Build
        run: pixi run export-web
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            output/index.js
            output/index.wasm